name: Generate DID Method Registry
on: [push]
jobs:
  validate-entries:
    runs-on: ubuntu-latest
    steps:
      - name: Begin spec-prod...
        uses: actions/checkout@v2
      - name: Setup Node 14...
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install did-spec-registries tooling...
        working-directory: tooling
        run: npm i
      - name: Validate did-spec-registries DID method entries
        working-directory: tooling
        run: npm run registry:validate
      - name: Generate did-spec-registries registry index
        working-directory: tooling
        run: npm run registry:generate:index
